### ISSUE TITLE
Make Editing/Removing Projects Available

### ISSUE THREAD

**Issue by nathanjh-28** [melisalarson/easy-do#27]
How do I rename a project or edit a project's settings?

**Comment by nathanjh-28** [comment]
When I am logged in, and I hit the logo on the upper left hand corner, I return to the login page... even though I am logged in.

**Comment by JimmySpann** [comment]
Hi Nathan, 

Congrats and thank you for being the first one to make a post!

**Currently, you cannot rename, edit, or delete a project. We hope to have this feature added soon. Until then, you can contact me or @melisalarson directly and we can make the changes to the database for you**. 

I labeled this Issue as enhancement (new feature/add on)  and help wanted. 

**-[Help Wanted] If you or anyone else wants to add this feature, I would love to include it and help you if you get stuck**

**Comment by JimmySpann** [comment]
> When I am logged in, and I hit the logo on the upper left hand corner, I return to the login page... even though I am logged in.

Can you put this into a new issue please? It'll make tracking each issue easier.

**Comment by JimmySpann** [comment]
Thanks to Natalie, this issue has been resolved!
