### ISSUE TITLE
Add-Project Button is Overlapping

### ISSUE THREAD

**Issue by avyrie** [melisalarson/easy-do#30]
The "Add Project" button overlaps with the "Current Projects" list (I took a screenshot, not sure if it will show up here). Maybe add some padding to the top and move the "Name Your Project" field down appropriately as well.
![image](https://user-images.githubusercontent.com/65050411/88086327-69b67000-cb44-11ea-9aea-d3138d446152.png)

**Comment by nataliesmyth** [comment]
![Screenshot 2020-07-23 04 17 03](https://user-images.githubusercontent.com/42597615/88265727-ff184800-cc9b-11ea-8797-dd03bca72f60.png)

something like that?

**Comment by JimmySpann** [comment]
Thanks Natalie! I'll update it this weekend!

**Comment by JimmySpann** [comment]
Natalie has fixed this issue
